name: build

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - master
    types: [opened, synchronize, closed]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-24.04
    name: Tests on ${{matrix.environment.elixir-version}} / CH ${{matrix.clickhouse}} / HTTP Adapter ${{matrix.adapter}}
    strategy:
      matrix:
        adapter: [HttpcAdapter, TeslaMintAdapter]
        clickhouse: [23.8, 24.12, 25.3]
        environment:
          # Elixir 1.18 supports OTP 25-27
          - elixir-version: 1.18
            otp-version: 27
          # Elixir 1.17 supports OTP 25-27
          - elixir-version: 1.17
            otp-version: 27
          # Elixir 1.16 supports OTP 24-26
          - elixir-version: 1.16
            otp-version: 26
          # Elixir 1.15 supports OTP 24-26
          - elixir-version: 1.15
            otp-version: 26
          # Elixir 1.14.5 supports OTP 26
          - elixir-version: 1.14.5
            otp-version: 26
          # oldest still supported version combination
          - elixir-version: 1.14
            otp-version: 24
    services:
      clickhouse:
        image: clickhouse/clickhouse-server:${{matrix.clickhouse}}
        ports:
        - 8123:8123
    steps:
    - uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with: ${{matrix.environment}}

    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps/
        key: deps-${{ runner.os }}-${{ matrix.environment.otp-version }}-${{ matrix.environment.elixir-version }}-${{ hashFiles('**/mix.lock') }}

    - name: Restore build cache
      uses: actions/cache@v4
      with:
        path: _build/test/
        key: build-${{ runner.os }}-${{ matrix.environment.otp-version }}-${{ matrix.environment.elixir-version }}-${{ hashFiles('**/mix.lock') }}

    - name: Install dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        mix compile
        mix format --check-formatted

    - name: Run tests
      run: mix test
      env:
        PILLAR_HTTP_ADAPTER: ${{matrix.adapter}}
        MIX_ENV: test
        CLICKHOUSE_URL: "http://localhost:8123"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}